name: Helper Updater

on:
  push:
    branches: [ master ]

env:
  RELEASE_VERSION: ${{ github.run_number }}
  COMMIT_HASH: ${{ github.sha }}

jobs:
  build_and_push:
    name: Build master image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vanced/helper-kt:${{ env.RELEASE_VERSION }}, vanced/helper-kt:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Update image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull vanced/helper-kt:${{ env.RELEASE_VERSION }}
            docker service update --env-add VERSION='${{ env.RELEASE_VERSION }}' --env-add COMMIT='${{ env.COMMIT_HASH }}' --image vanced/helper-kt:'${{ env.RELEASE_VERSION }}' prod-helper