name: Helper Updater

on:
  push:
    branches: [ master ]

env:
  RELEASE_VERSION: ${{ github.run_number }}
  COMMIT_HASH: ${{ github.sha }}

jobs:
  build_and_push:
    name: Build master image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Helper Build
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
  
      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew jar
        
      - name: Push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vanced/helper-kt:${{ env.RELEASE_VERSION }}, vanced/helper-kt:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "release_version": "${{ env.RELEASE_VERSION }}", "commit_hash": "${{ env.COMMIT_HASH }}" }'
